### PR TITLE
feature: enable sse-c uploads by optionally disabling ssl checks

### LINKED ISSUE #5: Support SSE-C encrypted file uploads
Implement ssl = false in startup command as shown in https://github.com/CleverCloud/testcontainers-ceph/issues/2#issuecomment-1731321910

### PR DESCRIPTION
**Pull request by jarlah**
Fixes #5 

If using withSslDisabled(), modifies the demo script by using an entry point that runs sed on it to add two extra lines after a specific line.

- [x] Add integration tests that proves we can actually use this for something useful

links:

- https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-s3-policy-condition-key-require-restrict-server-side-encryption-customer-provided-keys-sse-c/
- https://catalog.us-east-1.prod.workshops.aws/workshops/aad9ff1e-b607-45bc-893f-121ea5224f24/en-US/s3/serverside/ssec

### CODE REVIEW

**Comment by brice-laurencin** [comment]
This looks great! thanks!

I'll switch to this container once this gets merged.

**Comment by brice-laurencin** [comment]
Sure, I can do a PR to your branch. I'll do this today.

**Comment by jarlah** [comment]
I just had to take a look, and it seems you have to use RGW_SSL_CERTIFICATE=generate or mount something that puts a certificate inside the container. And then also enable https if not enabled by default. Im just toying with it now, and will be happy to see what you have when that times.

**Comment by jarlah** [comment]
After my own investigations you must be a magician if you manage to get a unit test going. 🪄 seems aws java sdk requires https and it's not simple to setup https in ceph/demo. An alternative would be to setup nginx self signed in front, but then sdk complains about that too ;) But its fun to dive into things like this, dive into the deep end ;)

**Comment by jarlah** [comment]
@brice-laurencin I played around a little bit and this is what I managed to cough up .. https://github.com/jarlah/testcontainers-ceph/pull/9 .. :) it complains with bad signature when I try to use the proxy passed version ... ;)

**Comment by brice-laurencin** [comment]
Hey @jarlah, thanks for the investigations. Sadly IntelliJ does not want to build the repo, nothing found, no dependencies, no code. I will try to build it from CLI later, probably no sooner than Friday or next weekend :disappointed: 
I was able to have AWS SDK call the Ceph I started without SSL with little issue, we use it with integration tests. I'm using `software.amazon.awssdk:s3:2.20.72`.

**Comment by jarlah** [comment]
@brice-laurencin thanks for the hint. I didn't know it was an option at all to use anything else than the aws-java-sdk package ;) learning new stuff every day ;) Guess its simpler to use the s3 package ... About the IntelliJ and not building/recognising the project, it's based on java 1.8 to be binary compatible with older projects, like official Testcontainers-java is. So maybe because of that ? I will try to remove .m2 folder and reimport project into IntelliJ to see if it works. Im using community edition of IntelliJ.

**Comment by brice-laurencin** [comment]
I'm using community as well.
and the S3 dependency is actually coming with some quarkus plugin that we use, so we are not completely managing which one we use.

**Comment by jarlah** [comment]
I added the s3 dependency to make it easier for you to work with. the container tests is now using the s3 dependency and they are passing (at least locally here)

**Comment by jarlah** [comment]
what! I got it working :D :D Niiiiice :) no stress @brice-laurencin  I will push to this PR soon ;)

**Comment by jarlah** [comment]
this is sadly not possible to do with the newer aws-java-sdk, but I will see if I can add another suite for the newer sdk. However that suite will not test sse-c because the sdk requires https

**Comment by jarlah** [comment]
@brice-laurencin now its just waiting for the release 1.2.0 to propagate into nexus. Thanks for the help. It's better to have one good and maintained testcontainer for ceph than hundred ways to do it spread across ;) https://github.com/jarlah/testcontainers-ceph/releases/tag/1.2.0

**Comment by jarlah** [comment]
@brice-laurencin how do it go, did you try it out? not a big community addition this one maybe, but if you find it useful it would be great to know. Currently I'm working on the testcontainers for elixir repository of mine, but if there is anything im working in the same domain at the moment ;)

**Comment by brice-laurencin** [comment]
Hey @jarlah, very sorry for the huge delay.
I was able to use your container and it just works, with SSL disabled.

Thanks a lot!

**Pull request merged**
